=== AnnaEla/JD2018-12-10/src/by/it/skosirskiy/jd02_07/jku.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02.skosirskiy.by.it/somestring"
        xmlns:tag="http://jd02.skosirskiy.by.it/somestring"
        elementFormDefault="qualified"
>
    <element name="jku">
        <complexType>
            <sequence>
                <element name="clients" type="tag:Clients" maxOccurs="unbounded"/>
                <element name="dispatchers" type="tag:Dispatchers" maxOccurs="unbounded"/>
                <element name="brigades" type="tag:Brigades" maxOccurs="unbounded"/>
                <element name="workPlan" type="tag:WorkPlan" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Clients">
        <sequence>
            <element name="client" type="tag:Client" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Client">
        <sequence>
            <element name="loginClient" type="string"/>
            <element name="passwordClient" type="string"/>
            <element name="emailClient" type="string"/>
            <element name="adressClient" type="string"/>
            <element name="phoneClient" type="integer"/>
        </sequence>
    </complexType>

    <complexType name="Dispatchers">
        <sequence>
            <element name="dispatcher" type="tag:Dispatcher" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Dispatcher">
        <sequence>
            <element name="nameDdspatcher" type="string"/>
            <element name="loginDispatcher" type="string"/>
            <element name="passwordDispatcher" type="string"/>
            <element name="emailDispatcher" type="string"/>
            <element name="idNumberDispatcher" type="integer"/>
            <element name="accessLevel" type="string"/>
        </sequence>
    </complexType>

    <complexType name="Brigades">
        <sequence>
            <element name="brigade" type="tag:Brigade" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Brigade">
        <sequence>
            <element name="numberBrigade" type="integer"/>
            <element name="brigadier" type="string"/>
            <element name="phoneBrigadier" type="string"/>
            <element name="workers" type="tag:Workers" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Workers">
        <sequence>
            <element name="worker" type="tag:Worker" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Worker">
        <sequence>
            <element name="nameWorker" type="string"/>
            <element name="post" type="string"/>
            <element name="phoneWorker" type="integer"/>
        </sequence>
    </complexType>

    <complexType name="WorkPlan">
        <sequence>
            <element name="months" type="tag:Months" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Months">
        <sequence>
            <element name="month" type="tag:Month" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Month">
        <sequence>
            <element name="nameMonth" type="string"/>
            <element name="requests" type="tag:Requests" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Requests">
        <sequence>
            <element name="request" type="tag:Request" maxOccurs="10"/>
        </sequence>
    </complexType>
    <complexType name="Request">
        <sequence>
            <element name="idRequest" type="string"/>
            <element name="dataCreate" type="string"/>
            <element name="dataComplite" type="string"/>
            <element name="clientRequest" type="string"/>
            <element name="dispatcherRequest" type="string"/>
            <element name="brigadeRequest" type="integer"/>
            <element name="status" type="string"/>
        </sequence>
    </complexType>




</schema>

=== AnnaEla/JD2018-12-10/src/by/it/skosirskiy/jd02_07/jku+xsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<jku xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns="http://jd02.skosirskiy.by.it/somestring"
     xsi:schemaLocation="http://jd02.skosirskiy.by.it/somestring jku.xsd">
    <clients>
        <client>
            <loginClient>client1</loginClient>
            <passwordClient>123</passwordClient>
            <emailClient>Client1@yandex.ru</emailClient>
            <adressClient>Minsk kirova 2</adressClient>
            <phoneClient>2233445</phoneClient>
        </client>
        <client>
            <loginClient>client2</loginClient>
            <passwordClient>456</passwordClient>
            <emailClient>Client2@yandex.ru</emailClient>
            <adressClient>Minsk engelsa 1</adressClient>
            <phoneClient>2642235</phoneClient>
        </client>
        <client>
            <loginClient>client3</loginClient>
            <passwordClient>789</passwordClient>
            <emailClient>Client2@yandex.ru</emailClient>
            <adressClient>Minsk engelsa 1</adressClient>
            <phoneClient>2864525</phoneClient>
        </client>
    </clients>
    <dispatchers>
        <dispatcher>
            <nameDdspatcher>semen</nameDdspatcher>
            <loginDispatcher>dispatcher1</loginDispatcher>
            <passwordDispatcher>qwe</passwordDispatcher>
            <emailDispatcher>dispatcher1@yandex.ru</emailDispatcher>
            <idNumberDispatcher>089</idNumberDispatcher>
            <accessLevel>admin</accessLevel>
        </dispatcher>
        <dispatcher>
            <nameDdspatcher>pavel</nameDdspatcher>
            <loginDispatcher>dispatcher2</loginDispatcher>
            <passwordDispatcher>asd</passwordDispatcher>
            <emailDispatcher>dispatcher2@yandex.ru</emailDispatcher>
            <idNumberDispatcher>025</idNumberDispatcher>
            <accessLevel>moderator</accessLevel>
        </dispatcher>
        <dispatcher>
            <nameDdspatcher>sergei</nameDdspatcher>
            <loginDispatcher>dispatcher3</loginDispatcher>
            <passwordDispatcher>asd</passwordDispatcher>
            <emailDispatcher>dispatcher3@yandex.ru</emailDispatcher>
            <idNumberDispatcher>061</idNumberDispatcher>
            <accessLevel>moderator</accessLevel>
        </dispatcher>
    </dispatchers>
    <brigades>
        <brigade>
            <numberBrigade>1</numberBrigade>
            <brigadier>ivan ivanich</brigadier>
            <phoneBrigadier>291112222</phoneBrigadier>
            <workers>
                <worker>
                    <nameWorker>sidr</nameWorker>
                    <post>locksmith</post>
                    <phoneWorker>29101247</phoneWorker>

                </worker>

            </workers>
        </brigade>
        <brigade>
            <numberBrigade>2</numberBrigade>
            <brigadier>petr petrivich</brigadier>
            <phoneBrigadier>291112222</phoneBrigadier>
            <workers>
                <worker>
                    <nameWorker>john</nameWorker>
                    <post>Locksmith</post>
                    <phoneWorker>294445555</phoneWorker>
                </worker>
                <worker>
                    <nameWorker>sam</nameWorker>
                    <post>Mechanic</post>
                    <phoneWorker>291232222</phoneWorker>
                </worker>
                <worker>
                    <nameWorker>petr</nameWorker>
                    <post>Locksmith</post>
                    <phoneWorker>298888999</phoneWorker>
                </worker>
            </workers>
        </brigade>
    </brigades>
    <workPlan>
        <months>
            <month>
                <nameMonth>january</nameMonth>
                <requests>
                    <request>
                        <idRequest>1234</idRequest>
                        <dataCreate>01.01.19</dataCreate>
                        <dataComplite>12.01.19</dataComplite>
                        <clientRequest>client1</clientRequest>
                        <dispatcherRequest>dispatcher1</dispatcherRequest>
                        <brigadeRequest>1</brigadeRequest>
                        <status>complete</status>
                    </request>
                    <request>
                        <idRequest>2565</idRequest>
                        <dataCreate>03.01.19</dataCreate>
                        <dataComplite>15.02.19</dataComplite>
                        <clientRequest>client2</clientRequest>
                        <dispatcherRequest>dispatcher2</dispatcherRequest>
                        <brigadeRequest>2</brigadeRequest>
                        <status>wait</status>
                    </request>
                </requests>
            </month>
            <month>
                <nameMonth>February</nameMonth>
                <requests>
                    <request>
                        <idRequest>1234</idRequest>
                        <dataCreate>01.01.19</dataCreate>
                        <dataComplite>12.01.19</dataComplite>
                        <clientRequest>client3</clientRequest>
                        <dispatcherRequest>dispatcher1</dispatcherRequest>
                        <brigadeRequest>1</brigadeRequest>
                        <status>cancellation</status>
                    </request>
                    <request>
                        <idRequest>2565</idRequest>
                        <dataCreate>03.01.19</dataCreate>
                        <dataComplite>15.01.19</dataComplite>
                        <clientRequest>client2</clientRequest>
                        <dispatcherRequest>dispatcher2</dispatcherRequest>
                        <brigadeRequest>2</brigadeRequest>
                        <status>wait</status>
                    </request>
                </requests>
            </month>
        </months>
    </workPlan>
</jku>
