=== AnnaEla/JD2018-12-10/src/by/it/moroz/jd02/jd02_07/jd02_07_02/restaurant.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT restaurant ((client)+,admin)>
<!ELEMENT client (login,email,password,client_info)>
<!ELEMENT admin (login,password)>
<!ELEMENT login (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT client_info (firstName,secondName,address,phoneNumber,creditCard)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT secondName (#PCDATA)>
<!ELEMENT address (city,street,house,apartment)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT house (#PCDATA)>
<!ELEMENT apartment (#PCDATA)>
<!ELEMENT phoneNumber (#PCDATA)>
<!ELEMENT creditCard (#PCDATA)>

=== AnnaEla/JD2018-12-10/src/by/it/moroz/jd02/jd02_07/jd02_07_02/restaurant+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE restaurant SYSTEM "restaurant.dtd">
<restaurant>
    <client>
        <login>demo_client_1</login>
        <email>demo_client_1@demo.com</email>
        <password>demo</password>
        <client_info>
            <firstName>client_firstName</firstName>
            <secondName>client_secondName</secondName>
            <address>
                <city>client_city</city>
                <street>client_street</street>
                <house>3</house>
                <apartment>15</apartment>
            </address>
            <phoneNumber>375291234567</phoneNumber>
            <creditCard>3214435600013498</creditCard>
        </client_info>
    </client>
    <admin>
        <login>demo_admin</login>
        <password>demo</password>
    </admin>
</restaurant>
